name: fluid_dialog
description: A dialog that  can switch between multiple contents and animates size and alignment dynamically.
version: 1.1.0
repository: https://github.com/RoundedInfinity/fluid_dialog

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

screenshots:
  - description: "A cover image of the plugin"
    path: images/cover.png
  - description: "A GIF that showcases the use of fluid dialog"
    path: images/video.gif
